"""Joint metadata loader / cache for :class:`MuDataOOM`.

Reads the joint ``/obs``, ``/var``, ``/obsm``, ``/varm``, ``/obsp``,
``/varp``, ``/obsmap``, ``/varmap``, ``/uns`` groups out of a source
``.h5mu`` lazily, using anndata's standard scverse encoders so we get
back proper :class:`pandas.DataFrame` / :class:`numpy.ndarray` /
:class:`scipy.sparse` values.

Holding the loaded values per :class:`MuDataOOM` is cheap: joint
tables are dimensioned by ``n_obs`` × n_columns (a few MB at most for
1M cells), unlike per-modality `X` which can be hundreds of GB.

In-memory MuDataOOMs (built from a dict of :class:`AnnDataOOM`, no
source ``.h5mu``) instead get their joint state from explicit
assignments — the loader gracefully returns empty defaults when there
is no source path to read from.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping

import h5py
import numpy as np
import pandas as pd

try:
    from anndata.io import read_elem  # anndata >= 0.11
except ImportError:  # pragma: no cover - older anndata
    from anndata.experimental import read_elem


# Mapping-style joint groups → empty-default factory.
_DICT_KEYS: tuple[str, ...] = ("obsm", "varm", "obsp", "varp", "obsmap", "varmap", "uns")


def _empty_df() -> pd.DataFrame:
    return pd.DataFrame()


def _empty_dict() -> dict:
    return {}


class JointState:
    """Lazily-loaded, mutable mirror of the joint root-level groups.

    Each property is loaded on first access from the source ``.h5mu``
    via :func:`anndata.io.read_elem`; subsequent reads hit the cache.
    Writers (set obs/var/obsm[k] = …) bypass the source and store the
    new value in the cache directly, mimicking upstream
    :class:`mudata.MuData` semantics.
    """

    __slots__ = (
        "_source",
        "_obs",
        "_var",
        "_obsm",
        "_varm",
        "_obsp",
        "_varp",
        "_obsmap",
        "_varmap",
        "_uns",
        "_loaded",
    )

    def __init__(self, source_h5mu: Path | None = None):
        self._source = source_h5mu
        self._obs: pd.DataFrame | None = None
        self._var: pd.DataFrame | None = None
        self._obsm: dict[str, Any] | None = None
        self._varm: dict[str, Any] | None = None
        self._obsp: dict[str, Any] | None = None
        self._varp: dict[str, Any] | None = None
        self._obsmap: dict[str, Any] | None = None
        self._varmap: dict[str, Any] | None = None
        self._uns: dict[str, Any] | None = None
        # set of keys that have been resolved (cache hit allowed)
        self._loaded: set[str] = set()

    # ------------------------------------------------------------------
    # Loaders
    # ------------------------------------------------------------------
    def _read_from_source(self, key: str, default_factory):
        """Read ``/key`` from the source .h5mu, falling back to default."""
        if self._source is None or not self._source.exists():
            return default_factory()
        with h5py.File(self._source, "r") as f:
            if key not in f:
                return default_factory()
            try:
                return read_elem(f[key])
            except Exception:
                return default_factory()

    # ------------------------------------------------------------------
    # Properties — generated by hand to keep the slots layout cheap
    # ------------------------------------------------------------------
    @property
    def obs(self) -> pd.DataFrame:
        if "obs" not in self._loaded:
            self._obs = self._read_from_source("obs", _empty_df)
            self._loaded.add("obs")
        return self._obs

    @obs.setter
    def obs(self, value: pd.DataFrame) -> None:
        if not isinstance(value, pd.DataFrame):
            value = pd.DataFrame(value)
        self._obs = value
        self._loaded.add("obs")

    @property
    def var(self) -> pd.DataFrame:
        if "var" not in self._loaded:
            self._var = self._read_from_source("var", _empty_df)
            self._loaded.add("var")
        return self._var

    @var.setter
    def var(self, value: pd.DataFrame) -> None:
        if not isinstance(value, pd.DataFrame):
            value = pd.DataFrame(value)
        self._var = value
        self._loaded.add("var")

    def _dict_property(self, name: str) -> dict:
        attr = f"_{name}"
        if name not in self._loaded:
            setattr(self, attr, self._read_from_source(name, _empty_dict))
            self._loaded.add(name)
        return getattr(self, attr)

    def _set_dict_property(self, name: str, value: Mapping[str, Any]) -> None:
        attr = f"_{name}"
        setattr(self, attr, dict(value))
        self._loaded.add(name)

    @property
    def obsm(self) -> dict:
        return self._dict_property("obsm")

    @obsm.setter
    def obsm(self, value: Mapping[str, Any]) -> None:
        self._set_dict_property("obsm", value)

    @property
    def varm(self) -> dict:
        return self._dict_property("varm")

    @varm.setter
    def varm(self, value: Mapping[str, Any]) -> None:
        self._set_dict_property("varm", value)

    @property
    def obsp(self) -> dict:
        return self._dict_property("obsp")

    @obsp.setter
    def obsp(self, value: Mapping[str, Any]) -> None:
        self._set_dict_property("obsp", value)

    @property
    def varp(self) -> dict:
        return self._dict_property("varp")

    @varp.setter
    def varp(self, value: Mapping[str, Any]) -> None:
        self._set_dict_property("varp", value)

    @property
    def obsmap(self) -> dict:
        return self._dict_property("obsmap")

    @obsmap.setter
    def obsmap(self, value: Mapping[str, Any]) -> None:
        self._set_dict_property("obsmap", value)

    @property
    def varmap(self) -> dict:
        return self._dict_property("varmap")

    @varmap.setter
    def varmap(self, value: Mapping[str, Any]) -> None:
        self._set_dict_property("varmap", value)

    @property
    def uns(self) -> dict:
        return self._dict_property("uns")

    @uns.setter
    def uns(self, value: Mapping[str, Any]) -> None:
        self._set_dict_property("uns", value)
